### ISSUE TITLE
java.lang.InstantiationError: androidx.compose.foundation.pager.PagerState After upgrading navigation compose version to 2.7.0

### ISSUE THREAD

**Issue by shangmingchao** [jvziyaoyao/ImageViewer#16]
```
java.lang.InstantiationError: androidx.compose.foundation.pager.PagerState
                                         	at com.origeek.imageViewer.gallery.ImagePagerState.<init>(ImagePager.kt:39)
                                         	at com.origeek.imageViewer.gallery.ImageGalleryState.<init>(ImageGallery.kt:67)
                                         	at com.origeek.imageViewer.previewer.PreviewerPagerState.<init>(PreviewerPagerState.kt:24)
                                         	at com.origeek.imageViewer.previewer.PreviewerPagerState.<init>(PreviewerPagerState.kt:17)
                                         	at com.origeek.imageViewer.previewer.PreviewerTransformState.<init>(PreviewerTransformState.kt:36)
                                         	at com.origeek.imageViewer.previewer.PreviewerVerticalDragState.<init>(PreviewerVerticalDragState.kt:39)
                                         	at com.origeek.imageViewer.previewer.PreviewerVerticalDragState.<init>(PreviewerVerticalDragState.kt:30)
                                         	at com.origeek.imageViewer.previewer.ImagePreviewerState.<init>(ImagePreviewer.kt:61)
                                         	at com.origeek.imageViewer.previewer.ImagePreviewerState.<init>(ImagePreviewer.kt:56)
                                         	at com.origeek.imageViewer.previewer.ImagePreviewerKt$rememberPreviewerState$imagePreviewerState$1.invoke(ImagePreviewer.kt:101)
                                         	at com.origeek.imageViewer.previewer.ImagePreviewerKt$rememberPreviewerState$imagePreviewerState$1.invoke(ImagePreviewer.kt:100)
                                         	at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:88)
                                         	at com.origeek.imageViewer.previewer.ImagePreviewerKt.rememberPreviewerState(ImagePreviewer.kt:100)
                                         	at com.frank.u.ui.MainScreenKt.MainScreen(MainScreen.kt:53)
                                         	at com.frank.u.MainActivity$onCreate$1$1.invoke(MainActivity.kt:22)
                                         	at com.frank.u.MainActivity$onCreate$1$1.invoke(MainActivity.kt:21)
```

**Comment by jvziyaoyao** [comment]
> ```
> java.lang.InstantiationError: androidx.compose.foundation.pager.PagerState
>                                          	at com.origeek.imageViewer.gallery.ImagePagerState.<init>(ImagePager.kt:39)
>                                          	at com.origeek.imageViewer.gallery.ImageGalleryState.<init>(ImageGallery.kt:67)
>                                          	at com.origeek.imageViewer.previewer.PreviewerPagerState.<init>(PreviewerPagerState.kt:24)
>                                          	at com.origeek.imageViewer.previewer.PreviewerPagerState.<init>(PreviewerPagerState.kt:17)
>                                          	at com.origeek.imageViewer.previewer.PreviewerTransformState.<init>(PreviewerTransformState.kt:36)
>                                          	at com.origeek.imageViewer.previewer.PreviewerVerticalDragState.<init>(PreviewerVerticalDragState.kt:39)
>                                          	at com.origeek.imageViewer.previewer.PreviewerVerticalDragState.<init>(PreviewerVerticalDragState.kt:30)
>                                          	at com.origeek.imageViewer.previewer.ImagePreviewerState.<init>(ImagePreviewer.kt:61)
>                                          	at com.origeek.imageViewer.previewer.ImagePreviewerState.<init>(ImagePreviewer.kt:56)
>                                          	at com.origeek.imageViewer.previewer.ImagePreviewerKt$rememberPreviewerState$imagePreviewerState$1.invoke(ImagePreviewer.kt:101)
>                                          	at com.origeek.imageViewer.previewer.ImagePreviewerKt$rememberPreviewerState$imagePreviewerState$1.invoke(ImagePreviewer.kt:100)
>                                          	at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:88)
>                                          	at com.origeek.imageViewer.previewer.ImagePreviewerKt.rememberPreviewerState(ImagePreviewer.kt:100)
>                                          	at com.frank.u.ui.MainScreenKt.MainScreen(MainScreen.kt:53)
>                                          	at com.frank.u.MainActivity$onCreate$1$1.invoke(MainActivity.kt:22)
>                                          	at com.frank.u.MainActivity$onCreate$1$1.invoke(MainActivity.kt:21)
> ```

请更新到以下版本：
implementation 'com.github.jvziyaoyao:ImageViewer:1.0.2-alpha.5'

**Comment by shangmingchao** [comment]
> > ```
> > java.lang.InstantiationError: androidx.compose.foundation.pager.PagerState
> >                                          	at com.origeek.imageViewer.gallery.ImagePagerState.<init>(ImagePager.kt:39)
> >                                          	at com.origeek.imageViewer.gallery.ImageGalleryState.<init>(ImageGallery.kt:67)
> >                                          	at com.origeek.imageViewer.previewer.PreviewerPagerState.<init>(PreviewerPagerState.kt:24)
> >                                          	at com.origeek.imageViewer.previewer.PreviewerPagerState.<init>(PreviewerPagerState.kt:17)
> >                                          	at com.origeek.imageViewer.previewer.PreviewerTransformState.<init>(PreviewerTransformState.kt:36)
> >                                          	at com.origeek.imageViewer.previewer.PreviewerVerticalDragState.<init>(PreviewerVerticalDragState.kt:39)
> >                                          	at com.origeek.imageViewer.previewer.PreviewerVerticalDragState.<init>(PreviewerVerticalDragState.kt:30)
> >                                          	at com.origeek.imageViewer.previewer.ImagePreviewerState.<init>(ImagePreviewer.kt:61)
> >                                          	at com.origeek.imageViewer.previewer.ImagePreviewerState.<init>(ImagePreviewer.kt:56)
> >                                          	at com.origeek.imageViewer.previewer.ImagePreviewerKt$rememberPreviewerState$imagePreviewerState$1.invoke(ImagePreviewer.kt:101)
> >                                          	at com.origeek.imageViewer.previewer.ImagePreviewerKt$rememberPreviewerState$imagePreviewerState$1.invoke(ImagePreviewer.kt:100)
> >                                          	at androidx.compose.runtime.saveable.RememberSaveableKt.rememberSaveable(RememberSaveable.kt:88)
> >                                          	at com.origeek.imageViewer.previewer.ImagePreviewerKt.rememberPreviewerState(ImagePreviewer.kt:100)
> >                                          	at com.frank.u.ui.MainScreenKt.MainScreen(MainScreen.kt:53)
> >                                          	at com.frank.u.MainActivity$onCreate$1$1.invoke(MainActivity.kt:22)
> >                                          	at com.frank.u.MainActivity$onCreate$1$1.invoke(MainActivity.kt:21)
> > ```
> 
> 请更新到以下版本： implementation 'com.github.jvziyaoyao:ImageViewer:1.0.2-alpha.5'

好了，非常感谢
